In [4]:
import numpy as np
import cv2

In [11]:
image_file_path = 'images/fish.jpg'
color_to_replace = [[0, 200, 200], [255, 255, 255]]
replacement_color = [60, 255, 255]

In [17]:
# To load the image
image = cv2.imread(image_file_path)
image

array([[[225, 229, 218],
        [228, 232, 221],
        [226, 230, 219],
        ...,
        [225, 220, 205],
        [219, 214, 199],
        [219, 214, 199]],

       [[224, 228, 217],
        [226, 230, 219],
        [226, 230, 219],
        ...,
        [223, 218, 203],
        [217, 212, 197],
        [213, 208, 193]],

       [[224, 228, 217],
        [226, 230, 219],
        [225, 229, 218],
        ...,
        [239, 234, 219],
        [244, 239, 224],
        [236, 231, 216]],

       ...,

       [[  0,  15,  21],
        [  2,  18,  24],
        [  4,  21,  24],
        ...,
        [ 23,  52,  67],
        [ 12,  45,  60],
        [ 16,  42,  58]],

       [[  2,  14,  20],
        [  5,  19,  25],
        [  5,  19,  25],
        ...,
        [ 16,  47,  62],
        [ 17,  47,  58],
        [ 18,  48,  65]],

       [[  0,  14,  20],
        [  3,  17,  23],
        [  4,  18,  24],
        ...,
        [ 16,  48,  61],
        [ 20,  51,  66],
        [ 20,  51,  66]]

In [15]:
# Convert image to RGB
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
image_rgb

array([[[218, 229, 225],
        [221, 232, 228],
        [219, 230, 226],
        ...,
        [205, 220, 225],
        [199, 214, 219],
        [199, 214, 219]],

       [[217, 228, 224],
        [219, 230, 226],
        [219, 230, 226],
        ...,
        [203, 218, 223],
        [197, 212, 217],
        [193, 208, 213]],

       [[217, 228, 224],
        [219, 230, 226],
        [218, 229, 225],
        ...,
        [219, 234, 239],
        [224, 239, 244],
        [216, 231, 236]],

       ...,

       [[ 21,  15,   0],
        [ 24,  18,   2],
        [ 24,  21,   4],
        ...,
        [ 67,  52,  23],
        [ 60,  45,  12],
        [ 58,  42,  16]],

       [[ 20,  14,   2],
        [ 25,  19,   5],
        [ 25,  19,   5],
        ...,
        [ 62,  47,  16],
        [ 58,  47,  17],
        [ 65,  48,  18]],

       [[ 20,  14,   0],
        [ 23,  17,   3],
        [ 24,  18,   4],
        ...,
        [ 61,  48,  16],
        [ 66,  51,  20],
        [ 66,  51,  20]]

In [16]:
# Convert image to HSV color
image_hsv = cv2.cvtColor(image_rgb, cv2.COLOR_RGB2HSV)
image_hsv

array([[[ 79,  12, 229],
        [ 79,  12, 232],
        [ 79,  12, 230],
        ...,
        [ 98,  23, 225],
        [ 98,  23, 219],
        [ 98,  23, 219]],

       [[ 79,  12, 228],
        [ 79,  12, 230],
        [ 79,  12, 230],
        ...,
        [ 98,  23, 223],
        [ 98,  24, 217],
        [ 98,  24, 213]],

       [[ 79,  12, 228],
        [ 79,  12, 230],
        [ 79,  12, 229],
        ...,
        [ 98,  21, 239],
        [ 98,  21, 244],
        [ 98,  22, 236]],

       ...,

       [[ 21, 255,  21],
        [ 22, 234,  24],
        [ 26, 213,  24],
        ...,
        [ 20, 167,  67],
        [ 21, 204,  60],
        [ 19, 185,  58]],

       [[ 20, 230,  20],
        [ 21, 204,  25],
        [ 21, 204,  25],
        ...,
        [ 20, 189,  62],
        [ 22, 180,  58],
        [ 19, 184,  65]],

       [[ 21, 255,  20],
        [ 21, 222,  23],
        [ 21, 213,  24],
        ...,
        [ 21, 188,  61],
        [ 20, 178,  66],
        [ 20, 178,  66]]

In [19]:
# Mask For color to replace

mask_color = cv2.inRange(image_hsv, np.array(color_to_replace[0]), np.array(color_to_replace[1]))
mask_color

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [20]:
# Apply morphological transformations to remove small noise
kernel = np.ones((9, 9), np.uint8)
mask_color = cv2.morphologyEx(mask_color, cv2.MORPH_CLOSE, kernel)
mask_color = cv2.morphologyEx(mask_color, cv2.MORPH_OPEN, kernel)

In [22]:
# Convert replacement color to HSV format (if needed)
replacement_color_hsv = np.array(replacement_color)

In [23]:
# Change the color in the HSV image
image_hsv[mask_color > 0] = replacement_color_hsv

In [24]:
# Convert the HSV image back to RGB
image_rgb_new = cv2.cvtColor(image_hsv, cv2.COLOR_HSV2RGB)

In [25]:
# Save the output image
cv2.imwrite("output1.jpg", cv2.cvtColor(image_rgb_new, cv2.COLOR_BGR2RGB))

True